name: Docker Image CI
run-name: ${{ github.actor }} is psushing
on:
  push:
    branch: main
  pull_request:
    branch: main

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v
      - name: Build docker image
        runs: docker build -t hearthuz/summer-frontend:latest .
